# Generated by Django 3.1.4 on 2021-01-21 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('login', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('roles', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportEvents',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('number_of_events', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('quest', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('note', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('checksum', models.BigIntegerField()),
                ('application_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendar.applicationuser')),
                ('comments_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendar.comments')),
                ('import_events_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendar.importevents')),
            ],
        ),
    ]
